eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8084/eureka

    instance:
      preferIpAddress: true
      healthcheck:
        enabled: true

spring:
application:
name: CONFIG-DEfAULT
